### ISSUE TITLE
Flip left-right on display

### ISSUE THREAD

**Issue by billiegoose** [billiegoose/biotac_webgui#1]
Youngmoo commented that left and right appear to be reversed in the GUI.

**Comment by RyanYoung25** [comment]
The way I have it the finger is nail side up

**Comment by billiegoose** [comment]
Right. But apparently right and left are flipped? Oh! It would depend on
whether you are looking at it from the top or bottom. Youngmoo was holding
it so the squishy part was facing up. I think you showed it to me squishy
part down.

**Comment by RyanYoung25** [comment]
It was designed squishy part down...

**Comment by billiegoose** [comment]
You want to tell Youngmoo "You're using it wrong?" ;-)

**Comment by billiegoose** [comment]
Or flip it so it matches his expectations? ;-)

**Comment by RyanYoung25** [comment]
I think I have a better idea, and by me I mean John. I was gonna make two tables one nail up and one nail down because the nail down shows how it interacts if you press it on something like a table. John suggested a button that switches between the two and I like that idea so I'm gonna attempt that.

**Comment by billiegoose** [comment]
That's a great idea!
